# Core/Eureka Server Port (prod) : "배포설명" 확인

# Core Server Port
server:
  port: ${PORT_NUMBER}

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL_PROD}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # HikariCP 설정 (커넥션 풀)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      # create , update 금지 , prod 에선 None 고려
      ddl-auto: validate # validate 로 수정 (전체 entity  수정 후)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: off
    root: info

# Spring Boot Actuator 서버 상태(헬스) 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    redis:
      enabled: false
    rabbit:
      enabled: false
  info:
    env:
      enabled: true
