# Core Server Port
server:
  port: 9100

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: http://chaekmate:1234@localhost:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # HikariCP 설정 (커넥션 풀)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      # create , update 금지
      ddl-auto: validate # validate 로 수정 (전체 entity  수정 후)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# Spring Boot Actuator 서버 상태(헬스) 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    db:
      enabled: true
    redis:
      enabled: false
    rabbit:
      enabled: false

