spring:
  application:
    name: chaekmate-core

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_RANGE}
      password: ${REDIS_PASSWORD}

  config:
    import: "optional:configserver:"    # configserver import 활성화

  cloud:
    config:
      enabled: false # Config server 사용 설정 기본 비활성화

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

aladin:
  api:
    base-url: http://www.aladin.co.kr/ttb/api
    key: ${ALADIN_API_KEY}

toss:
  api:
    url: https://api.tosspayments.com/v1
  secret-key: ${TOSS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info

rabbitmq:
  exchange:
    name: cm-book-exchange
  queues:
    queue-name:  cm-book-1 # cm-book-2, cm-book-3
    routing-key:  cm-book-key-1 # cm-book-key-2, cm-book-key-3
