# Core/Eureka Server Port (prod) : "배포설명" 확인

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL_PROD}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # DBCP2 설정 (커넥션 풀)
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-total: 10
      min-idle: 2
      validation-query: SELECT 1
      test-on-borrow: true

  jpa:
    hibernate:
      # create , update 금지 , prod 에선 None 고려
      ddl-auto: none # validate 로 수정 (전체 entity  수정 후)
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: off
    root: info

# Spring Boot Actuator 서버 상태(헬스) 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    redis:
      enabled: false
    rabbit:
      enabled: true
  info:
    env:
      enabled: true

# ===== RabbitMQ 회원 설정 (Prod) =====
rabbitmq:
  member:
    exchange: prod-cm-member-fanout-exchange
